### ISSUE TITLE
DTC's not working

### ISSUE THREAD

**Issue by ViezeVingertjes** [0x8DEADF00D/obd2NET#2]
I tried getting the DTC's from OBDII Simulator, but it throws an exception.
The exception occurs at `Vehicle.cs:line 163` because the byte array is not long enough. (6 bytes, but it tries to copy 2x 3 bytes starting from index 1 as far as i can see right now.)

Havent read into that part of the protocol yet, so not be able to fix it at this time. Maybe someone can drop an suggestion on why this happens and i'm happy to create a pull request later on.

**Comment by abraaocaldas** [comment]
Which OBD simulator you are using?

**Comment by ViezeVingertjes** [comment]
The simulator included in this repository. (https://github.com/0x8DEADF00D/obd2NET/tree/master/tools/obdsimwindows)

I tried letting it read from index 0 instead of index 1, and it will get the first DTC correctly that way, yet all following codes are incorrect.

**Comment by ViezeVingertjes** [comment]
Made a pull request with a solution that works for me. See Diagnostic Trouble Code Fix #3 
I'm not sure where the difference comes from, but instead of 3 bytes, it takes 2 bytes per DTC on my side. (With the supplied simulator)

**Comment by ViezeVingertjes** [comment]
The regex in ControllerResponse only takes the last piece of information from the response. This causes the overwritten data bug in above mentioned pull request.

**Comment by ViezeVingertjes** [comment]
Fixed the above issue of the 3 DTC limit. Not in the regex form, so might be something to improve.

**Comment by ViezeVingertjes** [comment]
Fixed it, refactored it into an acceptable solution and created a pull request. Everything should work now.
